# Generated by Django 5.0.7 on 2024-07-22 19:47

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('good_day', models.BooleanField(default=False)),
                ('neutral_day', models.BooleanField(default=False)),
                ('nauseous', models.BooleanField(default=False)),
                ('fainting', models.BooleanField(default=False)),
                ('bed_bound', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'days',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=10)),
                ('zip_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid zip code in the format XXXXX or XXXXX-XXXX.', regex='^\\d{5}(?:-\\d{4})?$')])),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_item', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('favorite_meal', models.BooleanField(default=False)),
                ('water_intake', models.IntegerField(default=0)),
                ('salt_intake', models.IntegerField(default=0)),
                ('weather', models.CharField(max_length=200)),
                ('low_heart_rate', models.IntegerField(default=0)),
                ('high_heart_rate', models.IntegerField(default=0)),
                ('activity', models.BooleanField(default=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='pots_pal.day')),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.AddField(
            model_name='day',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='pots_pal.user'),
        ),
    ]
