# Generated by Django 5.0.7 on 2024-07-23 15:03

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots_pal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='favorite_activity_item',
        ),
        migrations.RemoveField(
            model_name='data',
            name='favorite_meal_item',
        ),
        migrations.AlterField(
            model_name='data',
            name='activity_item',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None), size=10),
        ),
        migrations.AlterField(
            model_name='data',
            name='meal_item',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None), size=10),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('activity_items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='pots_pal.customuser')),
            ],
            options={
                'db_table': 'favorite',
            },
        ),
    ]
