# Generated by Django 5.0.7 on 2024-07-25 13:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots_pal', '0002_alter_data_meal_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='activity_item',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=10),
        ),
    ]
