# Generated by Django 5.0.7 on 2024-07-25 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pots_pal', '0003_alter_data_activity_item'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('user', 'date')},
        ),
    ]
