# Generated by Django 5.0.7 on 2024-07-29 13:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots_pal', '0004_alter_day_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='activity_item',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='data',
            name='meal_item',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), default=list, size=None),
        ),
    ]
