# Generated by Django 5.0.7 on 2024-07-29 13:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pots_pal', '0005_alter_data_activity_item_alter_data_meal_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='activity_item',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='data',
            name='meal_item',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None),
        ),
    ]
